### ISSUE TITLE
Парсинг кейса 010_riemann_guessp

### ISSUE THREAD

**Issue by r-aax** [r-aax/py-avx512#10]

**Comment by r-aax** [comment]
Сначала нужно определить какой набор операций нужно добавить для поддержки данного кейса. Для начала там есть логические операции с предикатами.

**Comment by r-aax** [comment]
Комментарии я из кейса уберу - парсер их не ест, и не нужны они.

**Comment by abagrov** [comment]
done 176432d879dabf1cdcf53236dcb722bc85b8572b
