### ISSUE TITLE
Запуск всех кейсов

### ISSUE THREAD

**Issue by r-aax** [r-aax/py-avx512#13]
- Так как сейчас парсер работает достаточно хорошо, то можно удалить из test.py генерацию промежуточного представления вручную.
- В файле test.py должен выполняться запуск генерации всех кейсов. Результаты запуска нужно сохранить в директории (например out). Для каждого кейса (например для кейса 001_if.c) должен сгенерироваться файл результата (out/001_if.txt), содержащий: 1) текст кейса, 2) печать промежуточного представления.

**Comment by abagrov** [comment]
558aa914b89a7c1e326471c5c11f7e4599fdc14d
