### ISSUE TITLE
Приведение в порядок класса Operand.

### ISSUE THREAD

**Issue by r-aax** [r-aax/py-avx512#16]
Пока рассматриваются следующие виды операндов.
1. Входной параметр.
2. Выходной параметр.
3. Вещественный регистр.
4. Предикатный регистр.
5. Константа.

Тип операнда характеризуется полем `Kind`, которое принимает значения `i`, `o`, `r`, `p`, `c`.
Другие поля операнда: `Id` и `Val`.
1. Входной параметр. `Kind = i`, `Id` - имя параметра, `Val` - в процессе эмуляции. Печать: `i/a`.
2. Выходной параметр. `Kind = o`, `Id` - имя параметра, `Val` - в процессе эмуляции. Печать: `o/a`.
3. Вещественный регистр. `Kind = r`, `Id` - номер, `Val` - в процессе эмуляции. Печать: `r5`.
4. Предикатный регистр. `Kind = p`, `Id` - номер, `Val` - в процессе эмуляции. Печать: `p5`.
5. Константа. `Kind = c`, `Id = None`, `Val` - постоянное. Печать: `c.1.5`.

Поле `Name` убрать, поле `Producer` убрать, так как может быть несколько записей в операнд.

**Comment by r-aax** [comment]
Или поле Name ты завел для каких-то важных целей?

**Comment by abagrov** [comment]
@r-aax поле Name скорее для отладочных целей, чтобы сопоставлять регистр и переменную

**Comment by r-aax** [comment]
Если только для отладки, то лучше это поле убрать.
Вообще говоря, одной переменной может соответствовать более одного регистра. 
И наоборот, один регистр может обслуживать несколько не пересекающихся по времени жизни переменных.
