### ISSUE TITLE
Поддержка булевых переменных.

### ISSUE THREAD

**Issue by r-aax** [r-aax/py-avx512#22]
Кейс `021_bool`

В данном кейсе результат сравнения записывается сначала в переменную `bool`
В промежуточном представлении переменная типа `bool` должна превращаться в предикат.

То есть запись:

```
    bool p = a > b;

    if (p)
    {
```

это то же, что и 

```
    if (a > b)
    {
```

P.S. При векторизации предикаты будут преобразованы в векторные маски.

**Comment by abagrov** [comment]
добавил только поддержку, превращать лучше после парсера, в оптимизаторе, когда будет доступна связь между операциями
